// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_f2ee45d423bbf6641bfe8b89b197ac53_5780e0c3_a323_474f_a440_8a1fa82ac717 : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
			set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldPosition)coherenceComponent).value;
			if (!coherenceSync.HasParentWithCoherenceSync)
            {
                value += floatingOriginDelta;
            }
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (WorldPosition)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.value = Value;
			}
			else 
			{
				update.value = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}

	public class Binding_f2ee45d423bbf6641bfe8b89b197ac53_6cf6449e_e0af_479d_ab89_4793c9620607 : RotationBinding
	{
		public override string CoherenceComponentName => "WorldOrientation";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Quaternion Value
		{
			get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
			set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldOrientation)coherenceComponent).value;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (WorldOrientation)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.value = Value;
			}
			else 
			{
				update.value = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldOrientation();
		}
	}

	public class Binding_f2ee45d423bbf6641bfe8b89b197ac53_20d5e610_7f76_49cb_8bea_470256bc21ae : ScaleBinding
	{
		public override string CoherenceComponentName => "GenericScale";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get { return (UnityEngine.Vector3)(coherenceSync.coherenceLocalScale); }
			set { coherenceSync.coherenceLocalScale = (UnityEngine.Vector3)(value); }
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((GenericScale)coherenceComponent).value;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (GenericScale)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.value = Value;
			}
			else 
			{
				update.value = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new GenericScale();
		}
	}

	public class Binding_f2ee45d423bbf6641bfe8b89b197ac53_ddc36ca6_518e_49ed_96de_cca290715cc3 : DeepPositionBinding
	{
		private global::UnityEngine.Transform CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_146763691926684410";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get { return (UnityEngine.Vector3)(CastedUnityComponent.localPosition); }
			set { CastedUnityComponent.localPosition = (UnityEngine.Vector3)(value); }
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_146763691926684410)coherenceComponent).position;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_146763691926684410)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.position = Value;
			}
			else 
			{
				update.position = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_146763691926684410();
		}
	}

	public class Binding_f2ee45d423bbf6641bfe8b89b197ac53_f8e191f0_481c_4e55_9ba5_bcdde95a184f : DeepRotationBinding
	{
		private global::UnityEngine.Transform CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_146763691926684410";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override Quaternion Value
		{
			get { return (UnityEngine.Quaternion)(CastedUnityComponent.localRotation); }
			set { CastedUnityComponent.localRotation = (UnityEngine.Quaternion)(value); }
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_146763691926684410)coherenceComponent).rotation;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_146763691926684410)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.rotation = Value;
			}
			else 
			{
				update.rotation = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_146763691926684410();
		}
	}

	public class Binding_f2ee45d423bbf6641bfe8b89b197ac53_07a2111a_80ac_4afc_98ef_d3a03f6f2b1e : DeepScaleBinding
	{
		private global::UnityEngine.Transform CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_146763691926684410";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override Vector3 Value
		{
			get { return (UnityEngine.Vector3)(CastedUnityComponent.localScale); }
			set { CastedUnityComponent.localScale = (UnityEngine.Vector3)(value); }
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_146763691926684410)coherenceComponent).localScale;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_146763691926684410)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.localScale = Value;
			}
			else 
			{
				update.localScale = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_146763691926684410();
		}
	}

	public class Binding_f2ee45d423bbf6641bfe8b89b197ac53_d29c6b97_7628_48eb_a35f_1a4d023773f5 : DeepPositionBinding
	{
		private global::UnityEngine.Transform CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_4539323039338691254";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get { return (UnityEngine.Vector3)(CastedUnityComponent.localPosition); }
			set { CastedUnityComponent.localPosition = (UnityEngine.Vector3)(value); }
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_4539323039338691254)coherenceComponent).position;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_4539323039338691254)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.position = Value;
			}
			else 
			{
				update.position = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_4539323039338691254();
		}
	}

	public class Binding_f2ee45d423bbf6641bfe8b89b197ac53_8a073479_5cdf_4ac0_a9c9_84f405e15667 : DeepRotationBinding
	{
		private global::UnityEngine.Transform CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_4539323039338691254";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override Quaternion Value
		{
			get { return (UnityEngine.Quaternion)(CastedUnityComponent.localRotation); }
			set { CastedUnityComponent.localRotation = (UnityEngine.Quaternion)(value); }
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_4539323039338691254)coherenceComponent).rotation;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_4539323039338691254)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.rotation = Value;
			}
			else 
			{
				update.rotation = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_4539323039338691254();
		}
	}

	public class Binding_f2ee45d423bbf6641bfe8b89b197ac53_d829f2ba_37aa_4294_b177_bad309038083 : DeepScaleBinding
	{
		private global::UnityEngine.Transform CastedUnityComponent;

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_4539323039338691254";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override Vector3 Value
		{
			get { return (UnityEngine.Vector3)(CastedUnityComponent.localScale); }
			set { CastedUnityComponent.localScale = (UnityEngine.Vector3)(value); }
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_4539323039338691254)coherenceComponent).localScale;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, double time)
		{
			var update = (Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_4539323039338691254)coherenceComponent;
			if (RuntimeInterpolationSettings.IsInterpolationNone) 
			{
				update.localScale = Value;
			}
			else 
			{
				update.localScale = GetInterpolatedAt(time);
			}
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53_UnityEngine__char_46_Transform_4539323039338691254();
		}
	}


	[Preserve]
	public class CoherenceSyncPlayer__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53 : CoherenceSyncBaked
	{
		private SerializeEntityID entityId;
		private Logger logger = Log.GetLogger<CoherenceSyncPlayer__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53>();

		// Cached targets for commands

		private IClient client;
		private CoherenceBridge bridge;

		private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
		{
			["5780e0c3-a323-474f-a440-8a1fa82ac717"] = new Binding_f2ee45d423bbf6641bfe8b89b197ac53_5780e0c3_a323_474f_a440_8a1fa82ac717(),
			["6cf6449e-e0af-479d-ab89-4793c9620607"] = new Binding_f2ee45d423bbf6641bfe8b89b197ac53_6cf6449e_e0af_479d_ab89_4793c9620607(),
			["20d5e610-7f76-49cb-8bea-470256bc21ae"] = new Binding_f2ee45d423bbf6641bfe8b89b197ac53_20d5e610_7f76_49cb_8bea_470256bc21ae(),
			["ddc36ca6-518e-49ed-96de-cca290715cc3"] = new Binding_f2ee45d423bbf6641bfe8b89b197ac53_ddc36ca6_518e_49ed_96de_cca290715cc3(),
			["f8e191f0-481c-4e55-9ba5-bcdde95a184f"] = new Binding_f2ee45d423bbf6641bfe8b89b197ac53_f8e191f0_481c_4e55_9ba5_bcdde95a184f(),
			["07a2111a-80ac-4afc-98ef-d3a03f6f2b1e"] = new Binding_f2ee45d423bbf6641bfe8b89b197ac53_07a2111a_80ac_4afc_98ef_d3a03f6f2b1e(),
			["d29c6b97-7628-48eb-a35f-1a4d023773f5"] = new Binding_f2ee45d423bbf6641bfe8b89b197ac53_d29c6b97_7628_48eb_a35f_1a4d023773f5(),
			["8a073479-5cdf-4ac0-a9c9-84f405e15667"] = new Binding_f2ee45d423bbf6641bfe8b89b197ac53_8a073479_5cdf_4ac0_a9c9_84f405e15667(),
			["d829f2ba-37aa-4294-b177-bad309038083"] = new Binding_f2ee45d423bbf6641bfe8b89b197ac53_d829f2ba_37aa_4294_b177_bad309038083(),
		};

		private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings =
			new Dictionary<string, Action<CommandBinding, CommandsHandler>>();

		public CoherenceSyncPlayer__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53()
		{
		}

		public override Binding BakeValueBinding(Binding valueBinding)
		{
			if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
			{
				valueBinding.CloneTo(bakedBinding);
				return bakedBinding;
			}

			return null;
		}

		public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
		{
			if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
			{
				commandBindingBaker.Invoke(commandBinding, commandsHandler);
			}
		}

		public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName)
		{
			if (!usesLodsAtRuntime)
			{
				return null;
			}

			if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
	
			logger.Warning($"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");

			return null;
		}

		public override void Dispose()
		{
		}

		public override void Initialize(SerializeEntityID entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
		{
			this.logger = logger.With<CoherenceSyncPlayer__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53>();
			this.bridge = bridge;
			this.entityId = entityId;
			this.client = client;
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				default:
					logger.Warning($"[CoherenceSyncPlayer__char_32_Prefab_f2ee45d423bbf6641bfe8b89b197ac53] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
